---
title: "About"
---

Hello! My name is QingQuan Xia. 

A little bit about me:

I am a Christian who is saved through grace by the Lord Jesus Christ and holds that the Bible is the perfect literal word of God. I love discussing about the Bible with anyone who is interested!

I graduated from UC Berkeley in 2022 as an Engineering Physics and EECS major, and then worked at SpaceX as a software engineer on the Direct-to-cell Starlink team for 3 years, writing code for the PHY/MAC layers of the 4G LTE protocol. However, because I really like doing physics, I'm applying for a PhD as of Nov 2025. 

There are many mathematical tools I've learned and honed over the years that I want to gather in one place. As I continue to learn things, I'm planning to write them down as notes on this website so that I can refer back to them in the future and hopefully benefit a few others as well. 

Would be incredibly happy to receive feedback or questions! You can email me at "qingquanxia at gmail dot com".
