---
title: "3 Proofs of the Fundamental Theorem of Algebra"
date: 2023-03-10
toc: true
number-sections: false
---
{{< include /macros.qmd >}}

## Visualizing complex polynomials

Real polynomials are easy to visualize. They map the reals into the reals, so that the graph is a curve in $\RR^2$, which we can draw on a sheet of paper. A complex polynomial, however, maps the complex plane into the complex plane, so that its graph is 4-dimensional, hence impossible to plot. 

In order to not overwhelm our low-dimensional brains, we can look at how the polynomial transforms circles. In the plots below, we've focused on a one-dimensional circle in the domain with radius $R=1$, which lives in the complex plane. We color the circle so we can easily identify its shape, then transform it with the polynomial into its image, which also lives in the complex plane.

The simplest polynomials of the form $z^n$ will transform the unit circle by winding it $n$ times around the origin.

A polynomial with real coefficients will appear symmetric with respect to reflection about the x-axis. This is because if $p$ is a polynomial with real coefficients, then $p(z) = p(z^*)$.

If $|z|$ is small, then $p(z)$ will be dominated by the lowest order term, and all other terms will be swamped out. This is due to the simple fact that if $z = 1/100$, for example, then $z^1$ is a hundred times larger than $z^2$, which is in turn a hundred times larger than $z^3$. How small $|z|$ has to be before the lowest order term dominates depends on the values of the coefficients, but for any given polynomial, we are guaranteed some small number below which the lowest order term will dominate.

If $|z|$ is large, then $p(z)$ will be dominated the highest order term for similar reasons. If $z=100$, then $z^3$ is a hundred times larger than $z^2$, which is in turn a hundred times larger than $z$. 

## The Theorem

Every non-constant complex polynomial has a root.

## Proof

### Asymptotics based proof (real analysis)

Let $p(z) = a_0 + a_1 z^1 + \cdots + a_N z^N$ be a polynomial, where $N>0$. Consider the closed disc of radius $R$ centered at the origin. As $R$ grows indefinitely, the minimum value of $|p(z)|$ on the boundary of the disc will grow indefinitely as well. Let's pick $R$ large enough so that it contains a point $z_0$ for which $|p(z)|$ is minimum (such a point must exist because compact sets map to compact sets, which is the generalization of the extreme value theorem, which says closed bounded intervals map to closed bounded intervals). Now shift $z_0$ to the origin, so we have $q(z) = p(z+z_0) = b_0 + b_1 z^1 + \cdots + b_N z^N$. Suppose for contradiction that $b_0\neq 0$. Let's take $b_0=1$ without loss of generality. 

If $b_1$ were nonzero, then let $z=(-1)\epsilon$ for some small $\epsilon>0$. Because the first-degree term dominates, we have found a $p(z)$ which is less than our minimum at the origin, a contradiction. Hence we conclude $b_1=0$. 

If $b_2$ were nonzero, then let $z=(-1)^(1/2) \epsilon$ for some small $\epsilon>0$. Because the second-degree term dominates in the absence of $b_1$, we have found a $p(z)$ which is less than our minimum at the origin, a contradiction. Hence we conclude $b_2=0$. 

If $b_3$ were nonzero, then let $z=(-1)^(1/3) \epsilon$ for some small $\epsilon>0$. Because the third-degree term dominates in the absence of $b_1, b_2$, we have found a $|p(z)|$ which is less than our minimum at the origin, a contradiction. Hence we conclude $b_3=0$. 

...

In this way we can conclude that all terms except for the constant term are 0, which contradicts our assumption that $p(z)$ is non-constant. Hence $b_0=0$, so that $q(0) = 0$, so $p(z_0) = 0$. 


### Rubber band proof (algebraic topology)

Let $p(z)$ be a non-constant polynomial. Let $A_R$ be the circle of radius $R$, and consider its image under $p$. When $R=0$, $A_R$ consists only of the origin, and $p(A_R)$ consists only of $p(0)$. If $p(0)=0$, we are done. Otherwise, for small $R$, $p(A_R)$ is a small, possibly tightly-wound rubber band that does not enclose the origin. When $R$ expands though, there is a point when the $a_N z^N$ term dominates and $p(A_R)$ looks like almost a perfect circle enclosing the origin. There must have been a moment in the expansion when the rubber band touched the origin.


### As a trivial corollary to an obscure theorem (complex analysis)

Liouville's theorem: A bounded complex-valued function which is holomorphic (aka complex-differentiable) on the entire complex plane must be constant.

Corollary: Let $p(z)$ be a non-constant polynomial. Suppose for contradiction it does not have any roots. Consider the closed disc of radius $R$ centered at the origin. Grow $R$ large enough so that outside the disc, $|p(z)|$ is greater than $M$. Because the closed disc is compact, $|p(z)|$ has a minimum value $m$ inside the disc, which is greater than 0 per our assumption. Then $1/p(z)$ is holomorphic and bounded with magnitude at most $1/m$, so that by Liouville's theorem, it is constant, so $p(z)$ is also constant, a contradiction.


### Galois theory based proof (todo)

